### ISSUE TITLE
.run().then() callback provides no useful information

### ISSUE THREAD

**Issue by darkwing** [darkowlzz/zest-runner#30]
The callback provided to `then()` is simply returning `true`, even when there are errors in the scripts and such.  If a test fails, it would be great to be provided information about it.  Even better would be a result representing each step of the entire zest file, if it pass or failed, and if failed, what result was returned instead.

Thoughts?

**Comment by darkowlzz** [comment]
It's ready! Sorry for the delay. 
First thing, use https://github.com/darkowlzz/zest-runner in package.json dependencies, I haven't published the new code to npm yet.
Second, [this] is how the run result is represented.
The empty objects {}, don't have anything useful, they are things like variable assignment, find and replace, etc. 
[] represents block of statements with sub-statements, consisting of statements under `if` or `else` block. {} inside them are individual statements with appropriate result values.

```js
{
  "print": "inside loop html",
  "type": "ZestActionPrint"
}
```
This represents a ZestActionPrint statement. Just a print statement.

```js
{
  "result": false,
  "print": "boom!",
  "priority": "HIGH",
  "type": "ZestActionFail"
}
```
This represents a ZestActionFail statement which indicates failure and stops further execution of the script. `print` contains the failure message. `priority` could be used to show the severeness of the failure. A client could use different colors to indicate severity.

```js
{
  "result": false,
  "message": "FAILED Assert - Status Code: expected 201 got 200",
  "method": "GET",
  "url": "http://example.com/",
  "code": 200,
  "rtt": "1031 ms",
  "type": "ZestRequest"
 }
```
This is how the result of a http request is represented. `result` is the result of the assertions on the request and `message` describes the failure. This failure won't stop the script execution.

So you use it like this
```js
.run().then(function(result) {
  // parse the result
})
```

Is this good enough?

[this]: https://pastebin.mozilla.org/8823052

**Comment by darkwing** [comment]
Great!  Thank you!
